# Basic workflow
name: build

# Controls when the action will run
# Workflow begins with push or PR events
# Focuses on the master branch only
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Create one single job
# This job performs all necessary checks
jobs:
  build:
    # Use the latest version of Ubuntu on Microsoft Azure
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Performs all actions on different versions of Python
        python-version: ["3.10"]
    # Define the workflow steps
    steps:
    # Checkout the code of the repository
        - name: Check out Repository Code
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        # Run the linting tool
        - name: Check Markdown
          uses: DavidAnson/markdownlint-cli2-action@v4
          with:
            globs: writing/report.md
        - name: Check Spelling
          uses: zwaldowski/cspell-action@v1
          with:
            paths: "writing/report.md"
            config: .github/cspell.json
        # Setup Python for the current language version
        - name: Setup Python ${{ matrix.python-version }}
          if: always()
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python-version }}
        # Install pip
        - name: Install Pip
          if: always()
          run: |
            pip install -U pip
        # Run GatorGrader: see config/gatorgrader.yml
        - name: Run GatorGrader
          if: always()
          run:  |
            pip install gatorgrade
            gatorgrade --config config/gatorgrade.yml
